Repository dotCMS/core, pull requests merged in 2019-10, with the labels that each got.

#17416 Issue 17371 trying to go to a url map with 2 levels directly while logged in gives you a 404
  dotCMS/src/integration-test/java/com/dotcms/rest/api/v1/page/PageResourceTest.java
  dotCMS/src/main/java/com/dotmarketing/cms/urlmap/URLMapAPIImpl.java
  dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPIImpl.java
  dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/HTMLPageAssetRendered.java
  dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/HTMLPageAssetRenderedBuilder.java
  dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageView.java
  dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
Labels: Release : 5.2.1

#17405 #16129 added strikethrough for non-existing langs
  dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/relationship_field.jsp
Labels: Release : 5.3.0

#17505 Issue 17470 move tests to use hikari
  docker/tests/integration/postgres-docker-compose.yml
  dotCMS/build.gradle
  dotCMS/dependencies.gradle
  dotCMS/immutables.gradle
  dotCMS/src/integration-test/java/com/dotcms/datagen/ContentTypeDataGen.java
  dotCMS/src/integration-test/java/com/dotcms/util/TestInitialContext.java
  dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/business/ContentletAPITest.java
  libs/buildlibs/mssql-jdbc-6.2.2.jre8.jar
  libs/buildlibs/mysql-connector-java-5.1.37-bin.jar
  libs/buildlibs/ojdbc5.jar
  libs/buildlibs/postgresql-42.2.2.jar
Labels: Changelog, Release : 5.3.0

#17526 Issue 17510 cms anon checking
  dotCMS/src/integration-test/java/com/dotmarketing/business/PermissionAPITest.java
  dotCMS/src/integration-test/java/com/dotmarketing/business/UserAPITest.java
  dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/business/ContentletCheckInTest.java
  dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
  dotCMS/src/main/java/com/dotcms/rest/ContentResource.java
  dotCMS/src/main/java/com/dotmarketing/business/PermissionAPI.java
  dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java
Labels: Cat : Privacy, Changelog
