Repository dotCMS/core, pull requests merged in 2024-05, with the labels that each got.

#28445 build(deps) #28388 : [EPIC]: Review security-related PRs created by Dependabot
  bom/application/pom.xml
Labels: Team : Lunik

#28487 fix(edit-page-v2): Loop created by weak regex when navigating
  core-web/libs/portlets/edit-ema/portlet/src/lib/services/guards/edit-ema.guard.spec.ts
  core-web/libs/portlets/edit-ema/portlet/src/lib/services/guards/edit-ema.guard.ts
  core-web/libs/portlets/edit-ema/portlet/src/lib/utils/index.ts
Labels: Team : Lunik, OKR : Core Features, Priority : 1 Show Stopper

#28569 fix(edit-page-2): Experiments had dirty state when navigating to a variant
  core-web/libs/portlets/edit-ema/portlet/src/lib/dot-ema-shell/store/dot-ema.store.spec.ts
  core-web/libs/portlets/edit-ema/portlet/src/lib/dot-ema-shell/store/dot-ema.store.ts
  core-web/libs/portlets/edit-ema/portlet/src/lib/edit-ema-editor/edit-ema-editor.component.spec.ts
  core-web/libs/portlets/edit-ema/portlet/src/lib/edit-ema-editor/edit-ema-editor.component.ts
  core-web/libs/portlets/edit-ema/portlet/src/lib/shared/models.ts
Labels: Team : Lunik, OKR : Technical User Experience, Priority : 2 High
